services:
  - type: web
    name: kido-medical-backend
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DIALECT
        value: postgres
      - key: BREVO_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: API_URL
        sync: false
      - key: APPNAME
        value: Kido Medical
      - key: VERIFICATION_EMAIL
        sync: false 