export enum NotificationType {
  MESSAGE = "MESSAGE",
  APPOINTMENT_SCHEDULED = "APPOINTMENT_SCHEDULED",
  APPOINTMENT_APPROVED = "APPOINTMENT_APPROVED",
  APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED",
}
