export enum NotificationType {
  MESSAGE = 'MESSAGE',
  APPOINTMENT = 'APPOINTMENT',
  PRESCRIPTION = 'PRESCRIPTION',
  APPOINTMENT_APPROVED = 'APPOINTMENT_APPROVED',
  APPOINTMENT_CANCELED = 'APPOINTMENT_CANCELED'
}
